### ISSUE TITLE
Program is too hard-coded

### ISSUE THREAD

**Issue by xiurobert** [Hundotte/TDaT#1]
The page is at http://tdat.byethost10.com

Your program should use RegEx to handle user input as well as PHP and jQuery+AJAX to handle the user output. The page is too dark. 

Please make the enhancements. Thanks

**Comment by Hundotte** [comment]
What do you mean by "too hard-coded"? Also, the darkness is to create the
'creepy' effect. How do I use RegEx? Thanks for your response.

On Tue, Mar 22, 2016 at 6:06 PM, xiurobert <notifications@github.com> wrote:

> Your program should use RegEx to handle user input as well as PHP and
> jQuery+AJAX to handle the user output. The page is too dark.
>
> Please make the enhancements. Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Hundotte/TDaT/issues/1>
>



-- 
Keane Wong (13)

Headmaster of the FLES and Current President of the FLS
Subcomittee of the 1M MoR
I.T. Hero of 1M MoR

Fretta-Leesigne Society

-

*FLS Report Restricted Use & Data Protection Responsibilities:*
*All reports, analysis, MIS and data provided to you by the FLS in this
e-mail and its attachments (including links in this e-mail to files &
data contained on secured network shared folders) is strictly for the
internal business use of the intended recipient.  As it may contain
confidential and/or sensitive data you are not permitted to circulate,
forward or distribute this work product without prior consent of the FLS.
As a recipient of sensitive and/or customer related information you
acknowledge your responsibility for the ongoing protection and security of
the data.  Any encryption or password protection of the information is not
to be removed*



============================== Information in this message is

strictly confidential. It is intended solely for the person or the
entity to whom

it is addressed. If you are not the intended recipient, you are not to

disseminate, distribute or copy this communication. Please notify the

sender and delete the message and any other record of it from your

system immediately. ==============================
